<?php

namespace App\Http\Middleware;

use App\Services\KeyGeneratorService;
use Illuminate\Http\Request;

class UrlHubLinkChecker
{
    /**
     * Handle an incoming request.
     *
     * @return \Illuminate\Http\Response|\Illuminate\Http\RedirectResponse
     */
    public function handle(Request $request, \Closure $next)
    {
        // Ensure that unique random keys can be generated by checking the remaining
        // capacity of the key generator service. If the capacity is zero, it indicates
        // that no more unique keys can be generated.
        if (app(KeyGeneratorService::class)->remainingCapacity() === 0) {
            return redirect()->back()
                ->withFlashError(
                    __('Sorry, our service is currently under maintenance.'),
                );
        }

        return $next($request);
    }
}
