<?php

namespace Tests\Unit\Services;

use App\Exceptions\CouldNotGenerateUniqueKeyException;
use App\Models\Url;
use App\Services\BlockedStringService;
use App\Services\KeyGeneratorService;
use Illuminate\Support\Facades\File;
use PHPUnit\Framework\Attributes as PHPUnit;
use Tests\TestCase;

#[PHPUnit\Group('services')]
class KeyGeneratorServiceTest extends TestCase
{
    private const RESOURCE_PREFIX = 'zzz';

    private KeyGeneratorService $keyGen;

    private BlockedStringService $blocked;

    protected function setUp(): void
    {
        parent::setUp();

        $this->keyGen = app(KeyGeneratorService::class);
        $this->blocked = app(BlockedStringService::class);
    }

    #[PHPUnit\Test]
    public function keyGen_default(): void
    {
        $value = 'foo';

        // Scenario 1
        $hash = $this->keyGen->generate($value);
        $this->assertSame($this->keyGen->shortHash($value), $hash);

        // Scenario 2
        // If the string is already used as a short link keyword
        Url::factory()->create(['keyword' => $hash]);
        $mock = $this->partialMock(KeyGeneratorService::class);
        $mock->shouldReceive([
            'shortHash' => $hash,
            'randomString' => 'mocked_random_string',
        ]);

        $this->assertSame('mocked_random_string', $mock->generate($value));
    }

    /**
     * The length of the string generated by the generator is adjustable
     */
    #[PHPUnit\Test]
    public function keyGen_StringLength(): void
    {
        $inputString = 'foobar';
        $strLen = 8;
        settings()->fill(['key_len' => $strLen])->save();

        $actual = $this->keyGen->generate($inputString);
        $this->assertSame($strLen, strlen($actual));
        $this->assertNotSame(strlen($inputString), strlen($actual));
    }

    /**
     * Tests the scenario when a reserved keyword is used as a value for the
     * generation of a unique string. The random string should be used instead
     * of the reserved keyword.
     */
    #[PHPUnit\Test]
    public function keyGen_WithReservedKeyword(): void
    {
        $reserved_keyword = KeyGeneratorService::RESERVED_KEYWORD[0];

        $mock = $this->partialMock(KeyGeneratorService::class);
        $mock->shouldReceive([
            'shortHash' => $reserved_keyword,
            'randomString' => 'mocked_random_string',
        ]);

        $this->assertSame(
            'mocked_random_string',
            $mock->generate($reserved_keyword),
        );
    }

    /**
     * Tests the scenario when a blacklisted string is used as a value for the
     * generation of a unique string. The random string should be used instead
     * of the blacklisted string.
     */
    #[PHPUnit\Test]
    public function keyGen_WithBlacklistedString(): void
    {
        $blacklisted_string = 'blacklisted_keyword';
        config(['urlhub.blacklist_keyword' => [$blacklisted_string]]);

        $mock = $this->partialMock(KeyGeneratorService::class);
        $mock->shouldReceive([
            'shortHash' => $blacklisted_string,
            'randomString' => 'mocked_random_string',
        ]);

        $this->assertSame(
            'mocked_random_string',
            $mock->generate($blacklisted_string),
        );
    }

    /**
     * Tests the scenario when the KeyGeneratorService::generate() method is unable
     * to generate a unique string after the maximum number of attempts.
     */
    #[PHPUnit\Test]
    public function keyGen_MaxAttempts(): void
    {
        $this->expectException(CouldNotGenerateUniqueKeyException::class);

        $keyGenMock = $this->partialMock(KeyGeneratorService::class);

        // 1. Ensure the initial shortHash is considered "already taken"
        $keyGenMock->shouldReceive('shortHash')->once()->andReturn('taken_initial_hash');

        // 2. Ensure verify() always returns false, forcing the loop to continue.
        //    This will be called for 'taken_initial_hash' first, then for the random string.
        $keyGenMock->shouldReceive('verify')->andReturn(false);

        // 3. We expect randomString() to be called MAXIMUM_TRIES times
        //    before the exception is thrown.
        $keyGenMock->shouldReceive('randomString')
            ->times(KeyGeneratorService::MAXIMUM_TRIES)
            // The actual return value is not very important here because verify is mocked
            ->andReturn('any_random_string');

        $keyGenMock->generate('some_long_url');
    }

    /**
     * The `verify` function should return `false` when the string is already
     * used as a short link keyword
     */
    #[PHPUnit\Test]
    public function verify_StringIsAlreadyInUse(): void
    {
        $standardKey = 'fOo';
        Url::factory()->create(['keyword' => $standardKey, 'is_custom' => false]);
        $this->assertFalse($this->keyGen->verify($standardKey));
        $this->assertTrue($this->keyGen->verify(strtoupper($standardKey)));
        $this->assertTrue($this->keyGen->verify(strtolower($standardKey)));

        $customeKey = 'bAr';
        Url::factory()->create(['keyword' => $customeKey, 'is_custom' => true]);
        $this->assertFalse($this->keyGen->verify($customeKey));
        $this->assertFalse($this->keyGen->verify(strtoupper($customeKey)));
        $this->assertFalse($this->keyGen->verify(strtolower($customeKey)));
    }

    /**
     * The `verify` function should return `false` when the string is in
     * the disallow list.
     */
    #[PHPUnit\Test]
    public function verify_StringIsDisallowed(): void
    {
        // Reserved
        $value = KeyGeneratorService::RESERVED_KEYWORD[0];
        $this->assertFalse($this->keyGen->verify($value));
        $this->assertFalse($this->keyGen->verify(strtoupper($value)));

        // Blacklisted
        $value = 'foobar';
        config(['urlhub.blacklist_keyword' => [$value]]);
        $this->assertFalse($this->keyGen->verify($value));
        $this->assertFalse($this->keyGen->verify(strtoupper($value)));

        // Route
        $value = $this->blocked->routeList()->first();
        $this->assertFalse($this->keyGen->verify($value));
        $this->assertFalse($this->keyGen->verify(strtoupper($value)));

        // Public directory
        $value = self::RESOURCE_PREFIX.fake()->unique()->word();
        File::makeDirectory(public_path($value));
        $this->assertFalse($this->keyGen->verify($value));
        $this->assertFalse($this->keyGen->verify(strtoupper($value)));

        // File name in public directory
        $value = self::RESOURCE_PREFIX.fake()->unique()->word();
        File::put(public_path($value), '');
        $this->assertFalse($this->keyGen->verify($value));
        $this->assertFalse($this->keyGen->verify(strtoupper($value)));
    }

    #[PHPUnit\Test]
    public function totalKeywordSpaceUsed(): void
    {
        $keyLen = 3;

        settings()->fill(['key_len' => $keyLen])->save();
        Url::factory()->create(['keyword' => 'foo', 'is_custom' => false]); // 1
        Url::factory()->create(['keyword' => 'bar', 'is_custom' => true]); // 8
        $this->assertSame(9, $this->keyGen->totalKeywordSpaceUsed());

        // Character length does not meet criteria
        settings()->fill(['key_len' => $keyLen + 1])->save();
        $this->assertSame(0, $this->keyGen->totalKeywordSpaceUsed());
        settings()->fill(['key_len' => $keyLen - 1])->save();
        $this->assertSame(0, $this->keyGen->totalKeywordSpaceUsed());
    }

    #[PHPUnit\Test]
    public function standardKeywordSpaceUsed(): void
    {
        $keyLen = 3;

        settings()->fill(['key_len' => $keyLen])->save();
        Url::factory()->create(['keyword' => 'foo', 'is_custom' => false]);
        Url::factory()->create(['keyword' => 'bar', 'is_custom' => false]);
        $this->assertSame(2, $this->keyGen->standardKeywordSpaceUsed());

        // Character length does not meet criteria
        settings()->fill(['key_len' => $keyLen + 1])->save();
        $this->assertSame(0, $this->keyGen->standardKeywordSpaceUsed());
        settings()->fill(['key_len' => $keyLen - 1])->save();
        $this->assertSame(0, $this->keyGen->standardKeywordSpaceUsed());
    }

    #[PHPUnit\Test]
    public function customKeywordSpaceUsed(): void
    {
        $keyLen = 3;

        settings()->fill(['key_len' => $keyLen])->save();
        Url::factory()->create(['keyword' => 'abc', 'is_custom' => true]); // 8
        Url::factory()->create(['keyword' => 'a2c', 'is_custom' => true]); // 4
        Url::factory()->create(['keyword' => 'a-c', 'is_custom' => true]); // 4
        Url::factory()->create(['keyword' => 'a2-', 'is_custom' => true]); // 2
        Url::factory()->create(['keyword' => '-12', 'is_custom' => true]); // 1
        $this->assertSame(19, $this->keyGen->customKeywordSpaceUsed());

        // Character length does not meet criteria
        settings()->fill(['key_len' => $keyLen + 1])->save();
        $this->assertSame(0, $this->keyGen->customKeywordSpaceUsed());
        settings()->fill(['key_len' => $keyLen - 1])->save();
        $this->assertSame(0, $this->keyGen->customKeywordSpaceUsed());
    }

    #[PHPUnit\TestWith([2, 1, 1])]
    #[PHPUnit\TestWith([1, 2, 0])] // negative value
    #[PHPUnit\Test]
    public function capacity($max, $used, $expected): void
    {
        $mock = $this->partialMock(KeyGeneratorService::class);
        $mock->shouldReceive([
            'maxUniqueStrings' => $max,
            'disallowedKeywordSpaceUsed' => $used,
        ]);
        $actual = $mock->remainingCapacity();

        $this->assertSame($expected, $actual);
    }

    #[PHPUnit\TestWith([1, 2, 0])]
    #[PHPUnit\TestWith([3, 2, 1])]
    #[PHPUnit\TestWith([100, 99, 1])]
    #[PHPUnit\TestWith([100, 20, 80])]
    #[PHPUnit\TestWith([100, 100, 0])]
    #[PHPUnit\Test]
    public function remainingCapacity($capacity, $used, $expected): void
    {
        $mock = $this->partialMock(KeyGeneratorService::class);
        $mock->shouldReceive([
            'capacity' => $capacity,
            'totalKeywordSpaceUsed' => $used,
        ]);
        $actual = $mock->remainingCapacity();

        $this->assertSame($expected, $actual);
    }

    /**
     * Test calculation of maximum unique strings based on key length.
     *
     * Verifies that `maxUniqueStrings` correctly calculates the total possible
     * combinations for a short key length and returns `PHP_INT_MAX` when the
     * calculation would exceed the maximum integer value (tested with a long
     * key length).
     */
    #[PHPUnit\Test]
    public function maxUniqueStrings(): void
    {
        $charLen = strlen($this->keyGen::ALPHABET);

        // Test case 1: Short key length
        settings()->fill(['key_len' => 2])->save();
        $this->assertSame(pow($charLen, 2), $this->keyGen->maxUniqueStrings());

        // Test case 2: Long key length
        settings()->fill(['key_len' => 12])->save();
        $this->assertSame(PHP_INT_MAX, $this->keyGen->maxUniqueStrings());
    }

    #[PHPUnit\Test]
    public function disallowedKeywordSpaceUsed(): void
    {
        settings()->fill(['key_len' => 2])->save();

        $mock = $this->partialMock(KeyGeneratorService::class);
        $mock->shouldReceive([
            'routeCollisionList' => ['ab', 'foo'],
            'publicPathCollisionList' => ['cd', 'bar'],
        ]);
        $actual = $mock->disallowedKeywordSpaceUsed();

        // (2^2) * 2
        $this->assertSame(8, $actual);
    }

    public function tearDown(): void
    {
        $resources = File::glob(public_path(self::RESOURCE_PREFIX.'*'));
        foreach ($resources as $resource) {
            File::deleteDirectory($resource);
            File::delete($resource);
        }

        parent::tearDown();
    }
}
